# Generated by Django 4.0.3 on 2022-04-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_rename_body_post_content_remove_category_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=False),
        ),
    ]
