# Generated by Django 4.0.3 on 2022-04-05 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='body',
        ),
    ]
