# Generated by Django 4.0.3 on 2022-04-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_rename_content_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
