# Generated by Django 4.0.3 on 2022-04-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_category_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimages',
            name='post',
        ),
    ]
