# Generated by Django 4.0.3 on 2022-04-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
